version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - test_db
    environment:
      DB_URL: "postgresql://user:password@db:5432/dbname"

  test_db:
    image: postgres
    environment:
      POSTGRES_DB: test_dbname
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

  tests:
    build: .
    depends_on:
      - app
      - test_db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://test_user:test_password@test_db:5432/test_dbname"